// This file is generated by scripts/generate-overlay-test-cases.mjs.
// Add a <case-id>-comments.json under overlay-tests/fixtures, then rebuild.
// A same-name MP4 is optional; the UI supplies a silent timeline when it is absent.

export const VIDEO_CASES = {
  sm40437038: {
    label: "sm40437038",
    comments: "./fixtures/sm40437038-comments.json",
    video: "./fixtures/sm40437038.mp4",
  },
  sm6240144: {
    label: "sm6240144",
    comments: "./fixtures/sm6240144-comments.json",
    video: "./fixtures/sm6240144.mp4",
  },
  so31603984: {
    label: "so31603984",
    comments: "./fixtures/so31603984-comments.json",
    video: "./fixtures/so31603984.mp4",
  },
  so31723295: {
    label: "so31723295",
    comments: "./fixtures/so31723295-comments.json",
    video: "./fixtures/so31723295.mp4",
  },
} as const;

export const DEFAULT_VIDEO_CASE_ID = "sm6240144" as const;
export const DEFAULT_COMMENT_DATA_SOURCES = [VIDEO_CASES[DEFAULT_VIDEO_CASE_ID].comments] as const;

export type VideoCaseId = keyof typeof VIDEO_CASES;
